"""
Knowledge Distillation Pipeline for Transformer-to-MLP Compression
===================================================================

This module implements a knowledge distillation pipeline that compresses the heavy
Transformer into a lightweight MLP for microsecond Rust inference without accuracy
degradation. The distilled MLP safely quarantines degraded models before deployment.

Optimized for: AMD Ryzen AI 5, microsecond Rust FFI, 4GB Python RAM quota
Key Features:
- Teacher-student distillation from Transformer to MLP
- Accuracy preservation validation
- Model quarantine for degraded checkpoints
- ONNX export for Rust deployment
- Memory-bounded training pipeline

Author: Nautilus/Ray Trading Bot - Stage 36
"""

import os
import json
import time
from pathlib import Path
from typing import Dict, Any, Optional, Tuple, List
from dataclasses import dataclass
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset


# Constants
MAX_SEQUENCE_LENGTH = 100
INPUT_DIM = 10
HIDDEN_DIM_TEACHER = 128
HIDDEN_DIM_STUDENT = 64
OUTPUT_DIM = 3
TEMPERATURE = 4.0  # Distillation temperature
ALPHA = 0.7  # Balance between hard and soft targets
QUARANTINE_THRESHOLD = 0.95  # Minimum accuracy ratio for deployment


@dataclass
class DistillationConfig:
    """Configuration for knowledge distillation."""
    batch_size: int = 64
    epochs: int = 50
    learning_rate: float = 0.001
    weight_decay: float = 0.01
    temperature: float = TEMPERATURE
    alpha: float = ALPHA
    patience: int = 10  # Early stopping patience
    quarantine_threshold: float = QUARANTINE_THRESHOLD
    checkpoint_dir: str = "./distillation_checkpoints"
    quarantine_dir: str = "./quarantine_models"


class LightweightMLPStudent(nn.Module):
    """
    Lightweight MLP student network for deployment to Rust.
    Designed for microsecond inference with minimal memory footprint.
    """
    
    def __init__(
        self,
        input_dim: int = INPUT_DIM * MAX_SEQUENCE_LENGTH,  # Flattened LOB data
        hidden_dims: List[int] = None,
        output_dim: int = OUTPUT_DIM,
        dropout: float = 0.1
    ):
        super().__init__()
        
        if hidden_dims is None:
            hidden_dims = [256, 128, 64]
        
        self.input_dim = input_dim
        self.hidden_dims = hidden_dims
        self.output_dim = output_dim
        
        # Build MLP layers
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, hidden_dim),
                nn.BatchNorm1d(hidden_dim),
                nn.GELU(),
                nn.Dropout(dropout)
            ])
            prev_dim = hidden_dim
        
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
        
        # Memory estimation
        self._estimate_memory()
    
    def _estimate_memory(self) -> None:
        """Estimate model memory for 4GB quota compliance."""
        total_params = sum(p.numel() for p in self.parameters())
        param_mb = total_params * 4 / 1024 / 1024
        print(f"MLP Student parameters: {total_params:,}")
        print(f"MLP Student memory: {param_mb:.2f} MB")
        
        if param_mb > 500:  # Warn if student is too large
            print("WARNING: Student model approaching size limits!")
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass.
        
        Args:
            x: (batch, input_dim) flattened input
        """
        return self.network(x)
    
    def export_to_onnx(self, path: str, opset_version: int = 14) -> None:
        """Export model to ONNX for Rust deployment."""
        self.eval()
        
        dummy_input = torch.randn(1, self.input_dim)
        
        torch.onnx.export(
            self,
            dummy_input,
            path,
            opset_version=opset_version,
            do_constant_folding=True,
            input_names=['input'],
            output_names=['output'],
            dynamic_axes=None  # Fixed shape for deployment
        )
        
        print(f"Model exported to ONNX: {path}")
    
    def export_to_rust_struct(self, path: str) -> None:
        """
        Export weights as Rust-compatible struct.
        Generates Rust code that can be directly compiled.
        """
        self.eval()
        
        rust_code = []
        rust_code.append("// Auto-generated MLP weights for Rust inference")
        rust_code.append("// DO NOT EDIT - Generated by Knowledge Distillation Pipeline")
        rust_code.append("")
        rust_code.append("use ndarray::{Array2, Array1};")
        rust_code.append("")
        rust_code.append("#[derive(Clone, Debug)]")
        rust_code.append("pub struct DistilledMLP {")
        rust_code.append("    pub layers: Vec<MLPLayer>,")
        rust_code.append("}")
        rust_code.append("")
        rust_code.append("#[derive(Clone, Debug)]")
        rust_code.append("pub struct MLPLayer {")
        rust_code.append("    pub weights: Array2<f32>,")
        rust_code.append("    pub bias: Array1<f32>,")
        rust_code.append("    pub has_activation: bool,")
        rust_code.append("}")
        rust_code.append("")
        rust_code.append("impl DistilledMLP {")
        rust_code.append("    pub fn new() -> Self {")
        rust_code.append("        Self {")
        rust_code.append("            layers: vec![")
        
        layer_idx = 0
        for name, module in self.named_modules():
            if isinstance(module, nn.Linear):
                weights = module.weight.detach().numpy().astype(np.float32)
                bias = module.bias.detach().numpy().astype(np.float32)
                
                # Format weights as Rust array
                w_shape = weights.shape
                w_data = ", ".join(f"{w:.6e}" for w in weights.flatten())
                b_data = ", ".join(f"{b:.6e}" for b in bias)
                
                rust_code.append(f"                MLPLayer {{")
                rust_code.append(f"                    weights: Array2::from_shape_vec(")
                rust_code.append(f"                        ({w_shape[0]}, {w_shape[1]}),")
                rust_code.append(f"                        vec![{w_data}])")
                rust_code.append(f"                    .unwrap(),")
                rust_code.append(f"                    bias: Array1::from_vec(vec![{b_data}]),")
                rust_code.append(f"                    has_activation: true,")
                rust_code.append(f"                }},")
                
                layer_idx += 1
        
        rust_code.append("            ],")
        rust_code.append("        }")
        rust_code.append("    }")
        rust_code.append("}")
        
        with open(path, 'w') as f:
            f.write("\n".join(rust_code))
        
        print(f"Rust weights exported to: {path}")


class DistillationLoss(nn.Module):
    """
    Combined distillation loss: KL divergence for soft targets + CE for hard targets.
    """
    
    def __init__(self, temperature: float = TEMPERATURE, alpha: float = ALPHA):
        super().__init__()
        self.temperature = temperature
        self.alpha = alpha
        self.kl_div = nn.KLDivLoss(reduction='batchmean')
        self.ce = nn.CrossEntropyLoss()
    
    def forward(
        self,
        student_logits: torch.Tensor,
        teacher_logits: torch.Tensor,
        hard_labels: torch.Tensor
    ) -> torch.Tensor:
        """
        Compute combined distillation loss.
        
        Args:
            student_logits: Raw logits from student
            teacher_logits: Raw logits from teacher
            hard_labels: Ground truth labels
        """
        # Soft targets (KL divergence)
        soft_student = F.log_softmax(student_logits / self.temperature, dim=1)
        soft_teacher = F.softmax(teacher_logits / self.temperature, dim=1)
        soft_loss = self.kl_div(soft_student, soft_teacher) * (self.temperature ** 2)
        
        # Hard targets (Cross entropy)
        hard_loss = self.ce(student_logits, hard_labels)
        
        # Combined loss
        loss = self.alpha * soft_loss + (1 - self.alpha) * hard_loss
        
        return loss


class KnowledgeDistiller:
    """
    Main knowledge distillation trainer with quarantine support.
    """
    
    def __init__(
        self,
        teacher_model: nn.Module,
        student_model: LightweightMLPStudent,
        config: DistillationConfig,
        device: str = None
    ):
        self.teacher = teacher_model
        self.student = student_model
        self.config = config
        
        if device is None:
            self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        else:
            self.device = torch.device(device)
        
        self.teacher.to(self.device)
        self.student.to(self.device)
        
        # Freeze teacher
        for param in self.teacher.parameters():
            param.requires_grad = False
        
        # Optimizer for student
        self.optimizer = torch.optim.AdamW(
            self.student.parameters(),
            lr=config.learning_rate,
            weight_decay=config.weight_decay
        )
        
        # Learning rate scheduler
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer, mode='min', factor=0.5, patience=5
        )
        
        # Loss function
        self.criterion = DistillationLoss(config.temperature, config.alpha)
        
        # Training state
        self.best_accuracy = 0.0
        self.best_state = None
        self.patience_counter = 0
        self.training_history = []
        
        # Create directories
        Path(config.checkpoint_dir).mkdir(parents=True, exist_ok=True)
        Path(config.quarantine_dir).mkdir(parents=True, exist_ok=True)
    
    def train_epoch(self, dataloader: DataLoader) -> Dict[str, float]:
        """Train for one epoch."""
        self.student.train()
        self.teacher.eval()
        
        total_loss = 0.0
        correct = 0
        total = 0
        
        for batch_x, batch_y in dataloader:
            batch_x = batch_x.to(self.device)
            batch_y = batch_y.to(self.device)
            
            self.optimizer.zero_grad()
            
            # Get teacher predictions (soft targets)
            with torch.no_grad():
                teacher_output = self.teacher(batch_x)
                if len(teacher_output.shape) == 3:
                    teacher_output = teacher_output.mean(dim=1)
            
            # Get student predictions
            student_output = self.student(batch_x)
            
            # Compute loss
            loss = self.criterion(student_output, teacher_output, batch_y)
            
            # Backward pass
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.student.parameters(), max_norm=1.0)
            self.optimizer.step()
            
            # Track metrics
            total_loss += loss.item()
            _, predicted = student_output.max(1)
            correct += predicted.eq(batch_y).sum().item()
            total += batch_y.size(0)
        
        return {
            'loss': total_loss / len(dataloader),
            'accuracy': correct / total
        }
    
    @torch.no_grad()
    def validate(self, dataloader: DataLoader) -> Dict[str, float]:
        """Validate the student model."""
        self.student.eval()
        self.teacher.eval()
        
        total_loss = 0.0
        correct = 0
        total = 0
        
        for batch_x, batch_y in dataloader:
            batch_x = batch_x.to(self.device)
            batch_y = batch_y.to(self.device)
            
            # Get predictions
            teacher_output = self.teacher(batch_x)
            if len(teacher_output.shape) == 3:
                teacher_output = teacher_output.mean(dim=1)
            
            student_output = self.student(batch_x)
            
            # Compute loss
            loss = self.criterion(student_output, teacher_output, batch_y)
            
            # Track metrics
            total_loss += loss.item()
            _, predicted = student_output.max(1)
            correct += predicted.eq(batch_y).sum().item()
            total += batch_y.size(0)
        
        return {
            'loss': total_loss / len(dataloader),
            'accuracy': correct / total
        }
    
    def train(self, train_loader: DataLoader, val_loader: DataLoader) -> Dict[str, Any]:
        """
        Full training loop with early stopping and quarantine support.
        """
        print(f"Starting knowledge distillation...")
        print(f"Teacher params: {sum(p.numel() for p in self.teacher.parameters()):,}")
        print(f"Student params: {sum(p.numel() for p in self.student.parameters()):,}")
        print(f"Device: {self.device}")
        
        start_time = time.time()
        
        for epoch in range(self.config.epochs):
            epoch_start = time.time()
            
            # Train
            train_metrics = self.train_epoch(train_loader)
            
            # Validate
            val_metrics = self.validate(val_loader)
            
            # Update scheduler
            self.scheduler.step(val_metrics['loss'])
            
            # Log progress
            epoch_time = time.time() - epoch_start
            log_entry = {
                'epoch': epoch + 1,
                'train_loss': train_metrics['loss'],
                'train_accuracy': train_metrics['accuracy'],
                'val_loss': val_metrics['loss'],
                'val_accuracy': val_metrics['accuracy'],
                'time_sec': epoch_time
            }
            self.training_history.append(log_entry)
            
            print(f"Epoch {epoch+1}/{self.config.epochs} | "
                  f"Train Acc: {train_metrics['accuracy']:.4f} | "
                  f"Val Acc: {val_metrics['accuracy']:.4f} | "
                  f"Time: {epoch_time:.2f}s")
            
            # Check for improvement
            if val_metrics['accuracy'] > self.best_accuracy:
                self.best_accuracy = val_metrics['accuracy']
                self.best_state = {k: v.cpu().clone() for k, v in self.student.state_dict().items()}
                self.patience_counter = 0
                
                # Save best checkpoint
                checkpoint_path = os.path.join(
                    self.config.checkpoint_dir,
                    f"best_student_epoch_{epoch+1}.pt"
                )
                torch.save({
                    'epoch': epoch + 1,
                    'state_dict': self.best_state,
                    'accuracy': self.best_accuracy
                }, checkpoint_path)
            else:
                self.patience_counter += 1
            
            # Early stopping
            if self.patience_counter >= self.config.patience:
                print(f"Early stopping at epoch {epoch+1}")
                break
        
        total_time = time.time() - start_time
        
        # Load best weights
        if self.best_state is not None:
            self.student.load_state_dict(self.best_state)
        
        return {
            'best_accuracy': self.best_accuracy,
            'total_epochs': epoch + 1,
            'total_time_sec': total_time,
            'history': self.training_history
        }
    
    def evaluate_deployment_readiness(self, test_loader: DataLoader) -> Dict[str, Any]:
        """
        Evaluate if the distilled model is ready for deployment.
        Quarantines degraded models.
        """
        self.student.eval()
        self.teacher.eval()
        
        student_correct = 0
        teacher_correct = 0
        total = 0
        
        with torch.no_grad():
            for batch_x, batch_y in test_loader:
                batch_x = batch_x.to(self.device)
                batch_y = batch_y.to(self.device)
                
                # Teacher prediction
                teacher_out = self.teacher(batch_x)
                if len(teacher_out.shape) == 3:
                    teacher_out = teacher_out.mean(dim=1)
                _, teacher_pred = teacher_out.max(1)
                
                # Student prediction
                student_out = self.student(batch_x)
                _, student_pred = student_out.max(1)
                
                student_correct += student_pred.eq(batch_y).sum().item()
                teacher_correct += teacher_pred.eq(batch_y).sum().item()
                total += batch_y.size(0)
        
        student_accuracy = student_correct / total
        teacher_accuracy = teacher_correct / total
        accuracy_ratio = student_accuracy / max(teacher_accuracy, 1e-6)
        
        result = {
            'student_accuracy': student_accuracy,
            'teacher_accuracy': teacher_accuracy,
            'accuracy_ratio': accuracy_ratio,
            'deployment_ready': accuracy_ratio >= self.config.quarantine_threshold
        }
        
        print(f"\nDeployment Evaluation:")
        print(f"  Teacher Accuracy: {teacher_accuracy:.4f}")
        print(f"  Student Accuracy: {student_accuracy:.4f}")
        print(f"  Accuracy Ratio: {accuracy_ratio:.4f}")
        print(f"  Threshold: {self.config.quarantine_threshold}")
        print(f"  Deployment Ready: {result['deployment_ready']}")
        
        # Quarantine if degraded
        if not result['deployment_ready']:
            self.quarantine_model()
            result['quarantined'] = True
            print("  WARNING: Model quarantined due to accuracy degradation!")
        else:
            result['quarantined'] = False
        
        return result
    
    def quarantine_model(self) -> str:
        """Move degraded model to quarantine directory."""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        quarantine_path = os.path.join(
            self.config.quarantine_dir,
            f"quarantined_model_{timestamp}.pt"
        )
        
        torch.save({
            'state_dict': self.student.state_dict(),
            'timestamp': timestamp,
            'reason': 'accuracy_below_threshold'
        }, quarantine_path)
        
        print(f"Model quarantined to: {quarantine_path}")
        return quarantine_path
    
    def export_for_deployment(self, output_dir: str) -> Dict[str, str]:
        """Export validated model for Rust deployment."""
        paths = {}
        
        # ONNX export
        onnx_path = os.path.join(output_dir, "distilled_mlp.onnx")
        self.student.export_to_onnx(onnx_path)
        paths['onnx'] = onnx_path
        
        # Rust struct export
        rust_path = os.path.join(output_dir, "distilled_mlp_weights.rs")
        self.student.export_to_rust_struct(rust_path)
        paths['rust'] = rust_path
        
        # Config export
        config_path = os.path.join(output_dir, "model_config.json")
        with open(config_path, 'w') as f:
            json.dump({
                'input_dim': self.student.input_dim,
                'hidden_dims': self.student.hidden_dims,
                'output_dim': self.student.output_dim,
                'best_accuracy': self.best_accuracy
            }, f, indent=2)
        paths['config'] = config_path
        
        print(f"\nExported files:")
        for key, path in paths.items():
            print(f"  {key}: {path}")
        
        return paths


def create_synthetic_lob_data(num_samples: int = 10000) -> Tuple[np.ndarray, np.ndarray]:
    """Create synthetic LOB data for testing distillation."""
    # Flatten: batch * seq_len * features -> batch * (seq_len * features)
    X = np.random.randn(num_samples, MAX_SEQUENCE_LENGTH * INPUT_DIM).astype(np.float32)
    
    # Generate labels based on simple pattern
    y = np.zeros(num_samples, dtype=np.int64)
    for i in range(num_samples):
        sample_mean = X[i].mean()
        if sample_mean > 0.5:
            y[i] = 0  # Buy
        elif sample_mean < -0.5:
            y[i] = 1  # Sell
        else:
            y[i] = 2  # Hold
    
    return X, y


if __name__ == '__main__':
    print("=" * 60)
    print("Knowledge Distillation Pipeline Test")
    print("=" * 60)
    
    # Import teacher model
    from lob_transformer import LightweightLOBTransformer
    
    # Create models
    teacher = LightweightLOBTransformer(
        input_dim=INPUT_DIM,
        max_depth=MAX_SEQUENCE_LENGTH,
        hidden_dim=HIDDEN_DIM_TEACHER,
        output_dim=OUTPUT_DIM
    )
    
    student = LightweightMLPStudent(
        input_dim=INPUT_DIM * MAX_SEQUENCE_LENGTH,
        hidden_dims=[256, 128, 64],
        output_dim=OUTPUT_DIM
    )
    
    # Create config
    config = DistillationConfig(
        batch_size=64,
        epochs=20,  # Reduced for testing
        learning_rate=0.001,
        quarantine_threshold=QUARANTINE_THRESHOLD
    )
    
    # Create distiller
    distiller = KnowledgeDistiller(teacher, student, config)
    
    # Create synthetic data
    print("\nGenerating synthetic data...")
    X, y = create_synthetic_lob_data(5000)
    
    # Split data
    split = 4000
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]
    
    # Create dataloaders
    train_dataset = TensorDataset(
        torch.from_numpy(X_train),
        torch.from_numpy(y_train)
    )
    test_dataset = TensorDataset(
        torch.from_numpy(X_test),
        torch.from_numpy(y_test)
    )
    
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=64)
    
    # Train
    print("\nStarting distillation training...")
    results = distiller.train(train_loader, test_loader)
    
    # Evaluate deployment readiness
    print("\nEvaluating deployment readiness...")
    eval_result = distiller.evaluate_deployment_readiness(test_loader)
    
    # Export if ready
    if eval_result['deployment_ready']:
        print("\nExporting model for deployment...")
        export_paths = distiller.export_for_deployment("./exported_models")
    
    print("\nDistillation complete!")
