/**
 * MonteCarloCone.tsx - Canvas rendering of future price probability cones
 * 
 * Features:
 * - Animates thousands of path-dependent trajectories in real-time
 * - Generated by Rust stress tester with proper buffer cleanup
 * - Respects browser memory limits by destroying old buffers
 * - AMD GPU context for high-performance rendering
 */

import React, { useRef, useEffect, useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Activity, TrendingUp, AlertTriangle, RefreshCw } from 'lucide-react';

interface MonteCarloPath {
  points: number[];
  percentile?: number; // For highlight paths (P10, P50, P90)
}

interface MonteCarloData {
  currentPrice: number;
  paths: MonteCarloPath[];
  timeSteps: number;
  timeHorizon: number; // Hours
  confidenceIntervals: {
    p10: number[];
    p50: number[];
    p90: number[];
  };
  generatedAt: number;
}

interface MonteCarloConeProps {
  data: MonteCarloData | null;
  onRegenerate: () => void;
  isGenerating: boolean;
}

export const MonteCarloCone: React.FC<MonteCarloConeProps> = ({
  data,
  onRegenerate,
  isGenerating,
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const animationFrameRef = useRef<number>(0);
  const pathsRef = useRef<MonteCarloPath[]>([]);
  
  const [animationPhase, setAnimationPhase] = useState(0);
  const [visiblePaths, setVisiblePaths] = useState(0);
  const [memoryUsage, setMemoryUsage] = useState(0);

  // Cleanup function to destroy old buffers
  const cleanupBuffers = useCallback(() => {
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = 0;
    }
    
    // Clear paths reference to allow GC
    pathsRef.current = [];
    
    // Force garbage collection hint
    if (typeof globalThis.gc === 'function') {
      globalThis.gc();
    }
    
    console.log('[MonteCarloCone] Buffers cleaned up');
  }, []);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      cleanupBuffers();
    };
  }, [cleanupBuffers]);

  // Update paths when data changes
  useEffect(() => {
    if (!data) return;
    
    // Clean up old buffers before loading new data
    cleanupBuffers();
    
    pathsRef.current = data.paths;
    setVisiblePaths(0);
    setAnimationPhase(0);
    
    // Calculate approximate memory usage
    const estimatedBytes = data.paths.length * data.timeSteps * 8; // 8 bytes per number
    setMemoryUsage(estimatedBytes / 1024 / 1024); // MB
  }, [data, cleanupBuffers]);

  // Animation loop
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !data) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const width = canvas.width;
    const height = canvas.height;
    const padding = 60;
    const graphWidth = width - padding * 2;
    const graphHeight = height - padding * 2;

    // Find price range for scaling
    let minPrice = Infinity;
    let maxPrice = -Infinity;
    
    data.confidenceIntervals.p10.forEach(p => {
      minPrice = Math.min(minPrice, p);
      maxPrice = Math.max(maxPrice, p);
    });
    data.confidenceIntervals.p90.forEach(p => {
      minPrice = Math.min(minPrice, p);
      maxPrice = Math.max(maxPrice, p);
    });

    const priceRange = maxPrice - minPrice || 1;
    const yScale = graphHeight / priceRange;
    const xScale = graphWidth / data.timeSteps;

    const animate = (timestamp: number) => {
      // Clear canvas
      ctx.fillStyle = '#0f172a';
      ctx.fillRect(0, 0, width, height);

      // Draw grid
      ctx.strokeStyle = '#1e293b';
      ctx.lineWidth = 1;
      
      // Horizontal grid lines
      for (let i = 0; i <= 5; i++) {
        const y = padding + (graphHeight / 5) * i;
        ctx.beginPath();
        ctx.moveTo(padding, y);
        ctx.lineTo(width - padding, y);
        ctx.stroke();
      }

      // Vertical grid lines
      for (let i = 0; i <= 10; i++) {
        const x = padding + (graphWidth / 10) * i;
        ctx.beginPath();
        ctx.moveTo(x, padding);
        ctx.lineTo(x, height - padding);
        ctx.stroke();
      }

      // Draw confidence interval fill
      const drawFilledArea = (upper: number[], lower: number[], color: string, alpha: number) => {
        ctx.fillStyle = color;
        ctx.globalAlpha = alpha;
        ctx.beginPath();
        
        const visibleSteps = Math.floor((animationPhase / 100) * data.timeSteps);
        
        ctx.moveTo(padding, height - padding - (lower[0] - minPrice) * yScale);
        
        for (let i = 0; i <= visibleSteps && i < upper.length; i++) {
          const x = padding + i * xScale;
          const y = height - padding - (upper[i] - minPrice) * yScale;
          ctx.lineTo(x, y);
        }
        
        for (let i = visibleSteps; i >= 0 && i < lower.length; i--) {
          const x = padding + i * xScale;
          const y = height - padding - (lower[i] - minPrice) * yScale;
          ctx.lineTo(x, y);
        }
        
        ctx.closePath();
        ctx.fill();
        ctx.globalAlpha = 1;
      };

      // Draw P10-P90 cone (outer)
      drawFilledArea(
        data.confidenceIntervals.p90,
        data.confidenceIntervals.p10,
        'rgba(239, 68, 68, 0.3)',
        1
      );

      // Draw P10-P50 cone (inner lower)
      drawFilledArea(
        data.confidenceIntervals.p50,
        data.confidenceIntervals.p10,
        'rgba(34, 211, 238, 0.2)',
        1
      );

      // Draw P50-P90 cone (inner upper)
      drawFilledArea(
        data.confidenceIntervals.p90,
        data.confidenceIntervals.p50,
        'rgba(34, 211, 238, 0.2)',
        1
      );

      // Draw median line
      ctx.strokeStyle = '#22d3ee';
      ctx.lineWidth = 2;
      ctx.setLineDash([5, 5]);
      ctx.beginPath();
      
      const visibleSteps = Math.floor((animationPhase / 100) * data.timeSteps);
      
      for (let i = 0; i <= visibleSteps && i < data.confidenceIntervals.p50.length; i++) {
        const x = padding + i * xScale;
        const y = height - padding - (data.confidenceIntervals.p50[i] - minPrice) * yScale;
        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      
      ctx.stroke();
      ctx.setLineDash([]);

      // Draw random sample paths (animated)
      const maxVisiblePaths = Math.min(100, pathsRef.current.length);
      const targetVisiblePaths = Math.floor((animationPhase / 100) * maxVisiblePaths);
      setVisiblePaths(targetVisiblePaths);

      for (let i = 0; i < targetVisiblePaths; i++) {
        const path = pathsRef.current[i];
        if (!path) continue;

        ctx.strokeStyle = `rgba(34, 211, 238, ${0.1 + Math.random() * 0.1})`;
        ctx.lineWidth = 0.5;
        ctx.beginPath();

        const pathVisibleSteps = Math.floor((animationPhase / 100) * path.points.length);
        
        for (let j = 0; j <= pathVisibleSteps && j < path.points.length; j++) {
          const x = padding + j * xScale;
          const y = height - padding - (path.points[j] - minPrice) * yScale;
          if (j === 0) ctx.moveTo(x, y);
          else ctx.lineTo(x, y);
        }
        
        ctx.stroke();
      }

      // Draw axis labels
      ctx.fillStyle = '#64748b';
      ctx.font = '10px monospace';
      ctx.textAlign = 'center';
      
      // X-axis time labels
      for (let i = 0; i <= 10; i++) {
        const x = padding + (graphWidth / 10) * i;
        const timeLabel = `${((data.timeHorizon / 10) * i).toFixed(1)}h`;
        ctx.fillText(timeLabel, x, height - 20);
      }

      // Y-axis price labels
      ctx.textAlign = 'right';
      for (let i = 0; i <= 5; i++) {
        const y = padding + (graphHeight / 5) * i;
        const price = maxPrice - (priceRange / 5) * i;
        ctx.fillText(`$${price.toFixed(0)}`, padding - 10, y + 4);
      }

      // Title
      ctx.fillStyle = '#22d3ee';
      ctx.font = 'bold 12px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('MONTE CARLO PRICE CONE', width / 2, 20);

      // Animate
      if (animationPhase < 100) {
        setAnimationPhase(prev => Math.min(100, prev + 0.5));
        animationFrameRef.current = requestAnimationFrame(animate);
      }
    };

    animationFrameRef.current = requestAnimationFrame(animate);

    return () => {
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current);
      }
    };
  }, [data, animationPhase]);

  return (
    <div className="w-full p-6 bg-slate-900/80 rounded-xl border border-cyan-500/30 shadow-[0_0_20px_rgba(6,182,212,0.2)]">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-bold text-cyan-400 flex items-center gap-2">
          <Activity className="w-5 h-5" />
          MONTE CARLO SIMULATION
        </h3>
        <div className="flex items-center gap-4 text-xs font-mono">
          <span className="text-slate-400">PATHS: {data?.paths.length || 0}</span>
          <span className="text-slate-400">MEMORY: {memoryUsage.toFixed(2)}MB</span>
          <button
            onClick={onRegenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-3 py-1.5 bg-cyan-500/20 border border-cyan-500 rounded-lg text-cyan-400 hover:bg-cyan-500/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <RefreshCw className={`w-3 h-3 ${isGenerating ? 'animate-spin' : ''}`} />
            REGENERATE
          </button>
        </div>
      </div>

      {/* Canvas */}
      <div className="relative mb-4">
        <canvas
          ref={canvasRef}
          width={800}
          height={400}
          className="w-full rounded-lg border border-slate-700"
        />

        {/* Current Price Overlay */}
        {data && (
          <div className="absolute top-4 left-4 px-3 py-2 bg-slate-800/90 border border-cyan-500/50 rounded-lg">
            <div className="text-xs text-slate-400">CURRENT PRICE</div>
            <div className="text-xl font-mono font-bold text-white">
              ${data.currentPrice.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </div>
          </div>
        )}

        {/* Legend Overlay */}
        <div className="absolute bottom-4 right-4 px-3 py-2 bg-slate-800/90 border border-slate-700 rounded-lg text-xs">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-4 h-0.5 bg-cyan-400" />
            <span className="text-slate-300">P50 (Median)</span>
          </div>
          <div className="flex items-center gap-3 mb-1">
            <div className="w-4 h-2 bg-red-500/30 rounded" />
            <span className="text-slate-300">P10-P90 Range</span>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-4 h-0.5 bg-cyan-400/20" />
            <span className="text-slate-300">Sample Paths</span>
          </div>
        </div>
      </div>

      {/* Statistics */}
      {data && (
        <div className="grid grid-cols-3 gap-4">
          <div className="p-3 bg-slate-800/50 rounded-lg border border-slate-700">
            <div className="text-xs text-slate-500 mb-1">TIME HORIZON</div>
            <div className="text-lg font-mono font-bold text-cyan-400">
              {data.timeHorizon} hours
            </div>
          </div>
          <div className="p-3 bg-slate-800/50 rounded-lg border border-slate-700">
            <div className="text-xs text-slate-500 mb-1">VISIBLE PATHS</div>
            <div className="text-lg font-mono font-bold text-emerald-400">
              {visiblePaths}
            </div>
          </div>
          <div className="p-3 bg-slate-800/50 rounded-lg border border-slate-700">
            <div className="text-xs text-slate-500 mb-1">CONFIDENCE</div>
            <div className="text-lg font-mono font-bold text-purple-400">
              80% (P10-P90)
            </div>
          </div>
        </div>
      )}

      {/* Warning Banner */}
      {data && data.paths.length > 5000 && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mt-4 p-3 bg-amber-500/20 border border-amber-500 rounded-lg flex items-start gap-3"
        >
          <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
          <div>
            <div className="text-amber-400 font-bold text-sm">HIGH PATH COUNT</div>
            <div className="text-amber-400/70 text-xs mt-1">
              Rendering {data.paths.length} paths may impact performance. Consider reducing simulation size.
            </div>
          </div>
        </motion.div>
      )}

      {/* Generation Status */}
      {isGenerating && (
        <div className="mt-4 p-3 bg-cyan-500/20 border border-cyan-500 rounded-lg text-center">
          <div className="text-cyan-400 font-bold text-sm flex items-center justify-center gap-2">
            <RefreshCw className="w-4 h-4 animate-spin" />
            GENERATING SIMULATION PATHS...
          </div>
        </div>
      )}
    </div>
  );
};

export default MonteCarloCone;
