//! Smart Order Routing - Latency Arbitrage Detector
//! 
//! Implements a cross-venue latency arbitrage detector that exploits microsecond
//! price discrepancies between correlated assets using strict integer math to
//! prevent drift. Optimized for AMD Ryzen AI 5 with zero heap allocation in hot path.

use std::sync::atomic::{AtomicU64, AtomicBool, AtomicI64, Ordering};
use std::sync::Arc;

/// Maximum number of asset pairs to monitor
const MAX_PAIRS: usize = 50;

/// Minimum arbitrage threshold in nanodollars (0.01 USD)
const MIN_ARB_THRESHOLD_NS: i64 = 10_000_000;

/// Maximum age for arbitrage signal (nanoseconds)
const MAX_SIGNAL_AGE_NS: u64 = 100_000; // 100 microseconds

/// Correlated asset pair for arbitrage detection
#[derive(Clone, Copy, Debug)]
#[repr(C, align(64))]
pub struct AssetPair {
    /// First asset hash (e.g., BTC)
    pub asset_a_hash: u64,
    /// Second asset hash (e.g., ETH)
    pub asset_b_hash: u64,
    /// Historical correlation coefficient (fixed-point, scale 10^9)
    pub correlation_fp: i64,
    /// Ratio of prices (asset_a / asset_b) fixed-point
    pub price_ratio_fp: i64,
    /// Mean ratio for z-score calculation
    pub ratio_mean_fp: i64,
    /// Standard deviation of ratio (fixed-point)
    pub ratio_std_fp: i64,
    /// Last update timestamp
    pub last_update_ns: AtomicU64,
}

impl AssetPair {
    pub const fn new(asset_a: u64, asset_b: u64) -> Self {
        Self {
            asset_a_hash: asset_a,
            asset_b_hash: asset_b,
            correlation_fp: 0,
            price_ratio_fp: 0,
            ratio_mean_fp: 1_000_000_000, // 1.0 in fixed-point
            ratio_std_fp: 10_000_000,     // 0.01 in fixed-point
            last_update_ns: AtomicU64::new(0),
        }
    }

    /// Update correlation and ratio statistics (rolling window)
    #[inline(always)]
    pub fn update_stats(&mut self, price_a_ns: i64, price_b_ns: i64, timestamp_ns: u64) {
        let current_ratio = if price_b_ns > 0 {
            (price_a_ns * 1_000_000_000).wrapping_div(price_b_ns)
        } else {
            self.price_ratio_fp
        };

        // Exponential moving average for mean (alpha = 0.1 in fixed-point)
        let alpha = 100_000_000; // 0.1
        let one_minus_alpha = 900_000_000; // 0.9
        
        self.ratio_mean_fp = (self.ratio_mean_fp * one_minus_alpha + current_ratio * alpha)
            .wrapping_div(1_000_000_000);

        // Simplified std dev update (EMA of squared deviations)
        let deviation = current_ratio.wrapping_sub(self.ratio_mean_fp).abs();
        self.ratio_std_fp = (self.ratio_std_fp * one_minus_alpha + deviation * alpha)
            .wrapping_div(1_000_000_000);

        self.price_ratio_fp = current_ratio;
        self.last_update_ns.store(timestamp_ns, Ordering::Release);
    }

    /// Calculate z-score for current ratio
    #[inline(always)]
    pub fn z_score(&self) -> i64 {
        if self.ratio_std_fp == 0 {
            return 0;
        }
        let deviation = self.price_ratio_fp.wrapping_sub(self.ratio_mean_fp);
        (deviation * 1_000_000_000).wrapping_div(self.ratio_std_fp)
    }
}

/// Cross-venue price for a single asset
#[derive(Clone, Copy, Debug)]
#[repr(C, align(64))]
pub struct VenuePrice {
    /// Venue ID
    pub venue_id: u8,
    /// Price in nanodollars
    pub price_ns: i64,
    /// Quantity available at this price (nanounits)
    pub qty_ns: i64,
    /// Timestamp in nanoseconds
    pub timestamp_ns: u64,
    /// Sequence number
    pub sequence: u64,
}

impl VenuePrice {
    pub const fn new(venue_id: u8, price_ns: i64, qty_ns: i64, ts_ns: u64) -> Self {
        Self {
            venue_id,
            price_ns,
            qty_ns,
            timestamp_ns: ts_ns,
            sequence: 0,
        }
    }
}

/// Arbitrage signal generated by the detector
#[derive(Clone, Copy, Debug)]
#[repr(C, align(64))]
pub struct ArbSignal {
    /// Asset hash being arbitraged
    pub asset_hash: u64,
    /// Buy venue ID
    pub buy_venue: u8,
    /// Sell venue ID
    pub sell_venue: u8,
    /// Buy price in nanodollars
    pub buy_price_ns: i64,
    /// Sell price in nanodollars
    pub sell_price_ns: i64,
    /// Expected profit per unit (nanodollars)
    pub profit_per_unit_ns: i64,
    /// Maximum executable quantity (nanounits)
    pub max_qty_ns: i64,
    /// Signal timestamp
    pub timestamp_ns: u64,
    /// Signal validity flag
    pub valid: AtomicBool,
    /// Execution status (0=pending, 1=executing, 2=done, 3=failed)
    pub status: AtomicU64,
}

impl ArbSignal {
    #[inline(always)]
    pub fn is_valid(&self, current_time_ns: u64) -> bool {
        if !self.valid.load(Ordering::Acquire) {
            return false;
        }
        current_time_ns.wrapping_sub(self.timestamp_ns) < MAX_SIGNAL_AGE_NS
    }

    #[inline(always)]
    pub fn total_profit_ns(&self) -> i64 {
        self.profit_per_unit_ns
            .wrapping_mul(self.max_qty_ns)
            .wrapping_div(1_000_000_000)
    }
}

/// Main latency arbitrage detector
#[repr(C, align(64))]
pub struct LatencyArbDetector {
    /// Monitored asset pairs
    pairs: [Option<AssetPair>; MAX_PAIRS],
    /// Number of active pairs
    pair_count: usize,
    /// Latest prices per asset per venue (flattened: asset_idx * MAX_VENUES + venue_idx)
    latest_prices: [Option<VenuePrice>; MAX_PAIRS * 8],
    /// Pending arbitrage signals queue (lock-free ring buffer)
    signals: [Option<ArbSignal>; 128],
    /// Signal queue head
    signal_head: AtomicU64,
    /// Signal queue tail
    signal_tail: AtomicU64,
    /// Total arbitrage opportunities detected
    total_opportunities: AtomicU64,
    /// Total profit captured (nanodollars)
    total_profit_ns: AtomicI64,
    /// Minimum profit threshold
    min_profit_ns: i64,
    /// Enable/disable detector
    enabled: AtomicBool,
}

impl LatencyArbDetector {
    pub const fn new() -> Self {
        Self {
            pairs: [None; MAX_PAIRS],
            pair_count: 0,
            latest_prices: [None; MAX_PAIRS * 8],
            signals: [None; 128],
            signal_head: AtomicU64::new(0),
            signal_tail: AtomicU64::new(0),
            total_opportunities: AtomicU64::new(0),
            total_profit_ns: AtomicI64::new(0),
            min_profit_ns: MIN_ARB_THRESHOLD_NS,
            enabled: AtomicBool::new(true),
        }
    }

    /// Add a new asset pair to monitor
    #[inline(always)]
    pub fn add_pair(&mut self, asset_a: u64, asset_b: u64) -> bool {
        if self.pair_count >= MAX_PAIRS {
            return false;
        }
        self.pairs[self.pair_count] = Some(AssetPair::new(asset_a, asset_b));
        self.pair_count += 1;
        true
    }

    /// Update price for an asset at a specific venue
    #[inline(always)]
    pub fn update_price(
        &mut self,
        asset_idx: usize,
        venue_id: u8,
        price_ns: i64,
        qty_ns: i64,
        timestamp_ns: u64,
    ) {
        if !self.enabled.load(Ordering::Acquire) {
            return;
        }

        let price_idx = asset_idx * 8 + venue_id as usize;
        if price_idx >= self.latest_prices.len() {
            return;
        }

        self.latest_prices[price_idx] = Some(VenuePrice::new(
            venue_id,
            price_ns,
            qty_ns,
            timestamp_ns,
        ));

        // Check for arbitrage opportunities across venues
        self.check_cross_venue_arb(asset_idx, venue_id, timestamp_ns);

        // Check for statistical arb with correlated pairs
        self.check_statistical_arb(asset_idx, timestamp_ns);
    }

    /// Check for direct cross-venue arbitrage
    #[inline(always)]
    fn check_cross_venue_arb(&mut self, asset_idx: usize, updated_venue: u8, timestamp_ns: u64) {
        let base_idx = asset_idx * 8;
        
        // Find best bid and best ask across all venues
        let mut best_bid_price = i64::MIN;
        let mut best_bid_venue = 0u8;
        let mut best_bid_qty = 0i64;
        
        let mut best_ask_price = i64::MAX;
        let mut best_ask_venue = 0u8;
        let mut best_ask_qty = 0i64;

        for venue_offset in 0..8 {
            let idx = base_idx + venue_offset;
            if idx >= self.latest_prices.len() {
                continue;
            }
            
            if let Some(price) = self.latest_prices[idx] {
                if price.price_ns > best_bid_price {
                    best_bid_price = price.price_ns;
                    best_bid_venue = price.venue_id;
                    best_bid_qty = price.qty_ns;
                }
                if price.price_ns < best_ask_price {
                    best_ask_price = price.price_ns;
                    best_ask_venue = price.venue_id;
                    best_ask_qty = price.qty_ns;
                }
            }
        }

        // Check for crossed market (arbitrage opportunity)
        if best_bid_price > best_ask_price {
            let spread_ns = best_bid_price.wrapping_sub(best_ask_price);
            
            if spread_ns >= self.min_profit_ns && best_bid_venue != best_ask_venue {
                let max_exec_qty = best_bid_qty.min(best_ask_qty);
                
                // Generate arbitrage signal
                let signal = ArbSignal {
                    asset_hash: asset_idx as u64,
                    buy_venue: best_ask_venue,
                    sell_venue: best_bid_venue,
                    buy_price_ns: best_ask_price,
                    sell_price_ns: best_bid_price,
                    profit_per_unit_ns: spread_ns,
                    max_qty_ns: max_exec_qty,
                    timestamp_ns,
                    valid: AtomicBool::new(true),
                    status: AtomicU64::new(0),
                };

                self.push_signal(signal);
                self.total_opportunities.fetch_add(1, Ordering::Relaxed);
                self.total_profit_ns.fetch_add(
                    (spread_ns * max_exec_qty).wrapping_div(1_000_000_000),
                    Ordering::Relaxed,
                );
            }
        }
    }

    /// Check for statistical arbitrage with correlated pairs
    #[inline(always)]
    fn check_statistical_arb(&mut self, asset_idx: usize, timestamp_ns: u64) {
        for i in 0..self.pair_count {
            if let Some(pair) = &mut self.pairs[i] {
                // Check if this asset is part of the pair
                if pair.asset_a_hash as usize == asset_idx || pair.asset_b_hash as usize == asset_idx {
                    // Get current prices for both assets
                    let price_a = self.get_best_price(pair.asset_a_hash as usize);
                    let price_b = self.get_best_price(pair.asset_b_hash as usize);

                    if let (Some(pa), Some(pb)) = (price_a, price_b) {
                        pair.update_stats(pa.price_ns, pb.price_ns, timestamp_ns);

                        // Check for z-score divergence
                        let z = pair.z_score();
                        
                        // Z-score threshold of 2.0 (in fixed-point: 2_000_000_000)
                        if z.abs() > 2_000_000_000 {
                            // Statistical arbitrage opportunity
                            // This would trigger a pairs trade
                        }
                    }
                }
            }
        }
    }

    /// Get best price for an asset across all venues
    #[inline(always)]
    fn get_best_price(&self, asset_idx: usize) -> Option<VenuePrice> {
        let base_idx = asset_idx * 8;
        let mut best: Option<VenuePrice> = None;

        for offset in 0..8 {
            let idx = base_idx + offset;
            if idx >= self.latest_prices.len() {
                continue;
            }

            if let Some(price) = self.latest_prices[idx] {
                if best.is_none() || price.price_ns > best.unwrap().price_ns {
                    best = Some(price);
                }
            }
        }

        best
    }

    /// Push signal to lock-free ring buffer
    #[inline(always)]
    fn push_signal(&mut self, signal: ArbSignal) {
        let tail = self.signal_tail.load(Ordering::Acquire);
        let head = self.signal_head.load(Ordering::Acquire);
        
        // Check if buffer is full
        if tail.wrapping_sub(head) >= 128 {
            return; // Buffer full, drop signal
        }

        let idx = (tail % 128) as usize;
        self.signals[idx] = Some(signal);
        self.signal_tail.fetch_add(1, Ordering::Release);
    }

    /// Pop next valid signal from queue
    #[inline(always)]
    pub fn pop_signal(&self, current_time_ns: u64) -> Option<ArbSignal> {
        let head = self.signal_head.load(Ordering::Acquire);
        let tail = self.signal_tail.load(Ordering::Acquire);

        if head >= tail {
            return None; // Queue empty
        }

        let idx = (head % 128) as usize;
        
        if let Some(signal) = &self.signals[idx] {
            if signal.is_valid(current_time_ns) {
                let result = *signal;
                self.signal_head.fetch_add(1, Ordering::Release);
                return Some(result);
            } else {
                // Signal expired, skip it
                self.signal_head.fetch_add(1, Ordering::Release);
            }
        }

        None
    }

    /// Get statistics
    #[inline(always)]
    pub fn stats(&self) -> (u64, i64) {
        (
            self.total_opportunities.load(Ordering::Relaxed),
            self.total_profit_ns.load(Ordering::Relaxed),
        )
    }

    /// Enable/disable detector
    #[inline(always)]
    pub fn set_enabled(&self, enabled: bool) {
        self.enabled.store(enabled, Ordering::Release);
    }
}

/// Get current time in nanoseconds
#[inline(always)]
fn get_time_ns() -> u64 {
    use std::time::Instant;
    static START: once_cell::sync::Lazy<Instant> = once_cell::sync::Lazy::new(Instant::now);
    START.elapsed().as_nanos() as u64
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cross_venue_arbitrage() {
        let mut detector = LatencyArbDetector::new();
        detector.add_pair(0x12345678, 0x87654321);

        let ts = get_time_ns();

        // Simulate price discrepancy across venues
        // Venue 0: price = 100.00
        detector.update_price(0, 0, 100_000_000_000, 1_000_000_000, ts);
        
        // Venue 1: price = 99.90 (cheaper - arbitrage opportunity)
        detector.update_price(0, 1, 99_900_000_000, 1_000_000_000, ts + 1000);

        // Should have detected arbitrage
        let (opps, profit) = detector.stats();
        assert!(opps >= 1);
        assert!(profit > 0);
    }

    #[test]
    fn test_signal_queue() {
        let mut detector = LatencyArbDetector::new();
        let ts = get_time_ns();

        // Create artificial arbitrage
        detector.update_price(0, 0, 100_100_000_000, 1_000_000_000, ts);
        detector.update_price(0, 1, 100_000_000_000, 1_000_000_000, ts + 100);

        // Pop signal
        let signal = detector.pop_signal(ts + 200);
        assert!(signal.is_some());
        
        let sig = signal.unwrap();
        assert_eq!(sig.buy_venue, 1);
        assert_eq!(sig.sell_venue, 0);
        assert!(sig.profit_per_unit_ns > 0);
    }

    #[test]
    fn test_z_score_calculation() {
        let mut pair = AssetPair::new(0xAAA, 0xBBB);
        
        // Update with consistent ratios
        pair.update_stats(100_000_000_000, 50_000_000_000, 1000); // ratio = 2.0
        pair.update_stats(100_000_000_000, 50_000_000_000, 2000);
        pair.update_stats(100_000_000_000, 50_000_000_000, 3000);

        // Now introduce deviation
        pair.update_stats(110_000_000_000, 50_000_000_000, 4000); // ratio = 2.2

        let z = pair.z_score();
        assert!(z.abs() > 0); // Should have some z-score
    }
}
